export const products = [
    {
        name: 'SMC208',
        imageText: 'SIMULADOR CESSNA CARAVAN C208',
        description: 'Simulador capaz de reproduzir procedimentos de IFR, familiarização e sistemas baseados na aeronave real.',
        imageAlt: 'Simulador do Cessna Caravan C208 em um ambiente escuro.',
        price: 'Sob Consulta',
        imageSrc: "/imagens/SMC208.jpg",
    },
    {
        name: 'SMB58 G1000',
        imageText: 'SIMULADOR BARON 58 G1000',
        description: 'Simulador multi-motor, modelo B58 G1000. Completo para procedimentos IFR.',
        imageAlt: 'Painel de um simulador do Baron 58 com telas G1000.',
        price: 'Sob Consulta',
        imageSrc: "/imagens/B58G1000.jpg",
    },
    {
        name: 'SMB58',
        imageText: 'SIMULADOR BARON 58',
        description: 'Simulador multi-motor, modelo B58. Completo para procedimentos IFR.',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/B58.jpg",
    },
    {
        name: 'SMC172',
        imageText: 'SIMULADOR CESSNA 172',
        description: 'Deixe seu voo ainda mais real! Simulador completo para realização de procedimentos VFR e IFR.',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/C172.jpg",
    },
    {
        name: 'SMC172 G1000',
        description: 'Deixe seu voo ainda mais real! Simulador completo para realização de procedimentos VFR e IFR.',
        imageText: 'SIMULADOR CESSNA 172 G1000',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/C172G1000.jpg",
    },
    {
        name: 'SMC172C',
        imageText: 'SIMULADOR CESSNA 172C',
        description: 'Desenvolvido junto à aeroclube, simulador compacto ideal para estudos ou para quem tem pouco espaço em casa!',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/C172C.jpg",
    },





    
    {
        name: 'SMG1000c',
        imageText: 'SIMULADOR G1000 CUSTOM',
        description: 'Simulador GlassCockpit, com PFD e MFD, alta tecnologia para um aviônico completo.',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'SMSEN2',
        imageText: 'SIMULADOR PIPER SENECA II',
        description: 'Simulador capaz de reproduzir procedimentos de IFR, familiarização e sistemas baseados na aeronave real.',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'KIT AS350',
        imageText: 'MFSIM - Comandos AS350',
        description: 'Comandos de voo para asa rotativa, com alta precisção e robustez!',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/AS350.jpg",
    },
    {
        name: 'RADIO STACK',
        imageText: 'MFSIM - Radio Stack + GNS430',
        description: 'Aviônico completo com frequências de comunicação, navegação, incluindo autopilot e sistema de GNS430 completo.',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'GNS430',
        imageText: 'MFSIM - GNS430',
        description: 'Equipamento de navegação, COM1/NAV1 compatível com Xplane, FSX e Prepar3D.',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'SMY172',
        imageText: 'Modulo de comandos principais - CUSTOM',
        description: 'Hardware refinado em metal e revestimento em couro. Indispensável para pilotos exigentes.',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/Y172.jpg",
    },
    {
        name: '737 YOKE',
        imageText: 'MFSIM - 737 Yoke',
        description: 'Sinta as emoções de ter o controle de um Boeing 737 em suas mãos',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'GFC700',
        imageText: 'MFSIM - GFC700 AP',
        description: 'Piloto automatico completo plug&play.',
        imageAlt: '',
        price: 'Sob Consulta',
        imageSrc: "/imagens/GFC700.jpg",
    },
    {
        name: 'RUDDER PEDAL SINGLE',
        imageText: 'MFSIM - Rudder Pedal Single',
        description: 'Preciso, freios independentes e graduais.',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'RUDDER PEDAL DUPLO',
        imageText: 'MFSIM - Pedal Duplo',
        description: 'Preciso, sincronizados, freios independentes e graduais.',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'SMI203',
        imageText: 'SIMULADOR IPANEMA 203 PARA PULVERIZAÇÃO',
        description: '',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'CIRRUS SR22',
        imageText: 'SIMULADOR CIRRUS SR22',
        description: '',
        imageAlt: '',
        price: 'Sob Consulta',
    },
    {
        name: 'TBM940',
        imageText: 'SIMULADOR TBM940 G3000',
        imageAlt: '',
        description: '',
        price: 'Sob Consulta',
    },
];